# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  vm_name = "jibjib-api"

  config.vm.define "#{vm_name}", primary: true do |master|
    master.vm.box = "bento/ubuntu-16.04"
    master.vm.hostname = vm_name + ".local"

    master.vm.synced_folder "keys", "/root/keys"
    master.vm.synced_folder "salt", "/root/salt"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "#{vm_name}"
    end

    master.vm.provision "install_salt", type: "shell", inline: <<-SHELL
      wget -q -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
      echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" > /etc/apt/sources.list.d/saltstack.list
      apt-get update
      apt-get install salt-ssh -y
    SHELL

    # If Go is needed, install manually with `vagrant provision --provision-with install_go`
    master.vm.provision "install_go", type: "shell", run: "never", inline: <<-SHELL
      wget -q -O - https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz | tar xzf - /usr/local
      echo "export PATH=/usr/local/go/bin:$PATH" > /home/vagrant/.profile
      mkdir /home/vagrant/go && chown vagrant:vagrant /home/vagrant/go
      echo "export GOPATH=/home/vagrant/go" > /home/vagrant/.bashrc
      echo "export GOBIN=/hom/vagrant/go/bin" > /home/vagrant/.bashrc
      chown vagrant:vagrant /home/vagrant/.bashrc
      chown vagrant:vagrant /home/vagrant/.profile
    SHELL
  end
end
