variable region {}
variable access_key {}
variable secret_key {}
variable ami {}
variable instance_type {}
variable query_instance_type {}
variable key_name {}
variable public_key {}
variable private_key {}
variable project_name {}
variable sg_desc {}
variable vpc {}
variable ssh_user {}
