variable region {}
variable access_key {}
variable secret_key {}
variable ami {}
variable instance_type {}
variable key_name {}
variable instance_name {}
variable project_name {}
variable sg_desc {}
variable vpc {}
